### ISSUE TITLE
Mouse wheel scroll Y not scrolling right on safari

### ISSUE THREAD

**Issue by finlamit** [oberonamsterdam/horizontal#9] opened 2020-02-13 14:04 UTC
Hi. Great plugin and works like a dream on Chrome & FF.
However, there is an issue with Safari. The Y axis wheel movement does not move the page to the right as it does on Chrome & FF. Is this a know bug/is there a fix?
Thanks.

**Comment by finlamit** [comment] 2020-02-24 14:21
Hi. I was wondering if you had a quick solution to this problem?
Thanks M

**Comment by Richardvanwill** [comment] 2020-02-24 14:36
Hi @finlamit, thanks reporting this issue. Currently, we are not seeing this issue with our implementations of this package. Is there a specific version of Safari with which you are seeing this issue?

**Comment by finlamit** [comment] 2020-02-24 14:53
Thanks for getting back to be @Richardvanwill . The version I safari am using is 13.0.4.

**Comment by Richardvanwill** [comment] 2020-02-24 15:37
Ok tnx. I'm afraid we don't have a quick solution available right now, but we're going to look into this. Might take some time though (a few weeks maybe). We're also happy to accept pull requests if anyone would care to look into this before we get to it.

**Comment by finlamit** [comment] 2020-02-24 15:47
Thanks @Richardvanwill . Thats perfect. Ill take a look myself if I get a chance.

**Comment by jamespurnama1** [comment] 2020-02-25 16:22
I think I am having the same issue. I'm using npm webpack with
`import HorizontalScroll from '@oberon-amsterdam/horizontal';`
i did see the DOM in the <html> tag received the  `__horizontal-container-3456` class.
So it is imported in Safari after all?

**Comment by septemberservices** [comment] 2020-04-13 08:51
I'm having the same issue, the scroll event is fired on safari but the container only moves 1px to the right.

**Comment by kheiraoudejans** [comment] 2020-05-25 08:05
@septemberservices @jamespurnama1  @finlamit 
Hi! 
We can't reproduce that it's not working on Safari at the moment. Could you guys provide us with the code that you're using and what device you are on? 
Thanks in advance!

**Comment by deodat** [comment] 2020-05-25 09:03
Hello, 
I'm having the same issue on version 13.1 of Safari on macOsX 10.15.4 Catalina with this code :
`
import HorizontalScroll from '@oberon-amsterdam/horizontal';
const content = document.querySelector('.site-content');
const horizontal = new HorizontalScroll({ container: content });
`

**Comment by deodat** [comment] 2020-05-25 09:32
In fact, I've noticed the issue with Safari is with the vertical scroll on trackpad, not with the mousewheel.

**Comment by jariz** [comment] 2020-05-25 14:40
Should be fixed on the recently published `1.0.3`, reopen if this still arises.

**Closed by jariz** 2020-05-25 14:40 UTC
