### ISSUE TITLE
There is a way to disable it?

### ISSUE THREAD

**Issue by Koronos** [oberonamsterdam/horizontal#12] opened 2020-04-22 21:08 UTC
I'm creating an horizontal website, it becomes a vertical website if the viewport is less than 992. I create an event listener in resize event.

```
let scroll = null;

function enableScroll() {
    if (window.innerWidth > 992) {
        scroll = new HorizontalScroll({
            preventVerticalScroll: false,
        });
    } else {
        scroll && scroll.destroy();
    }
}
```
It works from small to big viewport, but when I try to disable it, the function "destroy" doesn't work, and the website is cannot scroll vertically.

PD: I tried to use the preventVerticallScroll option, and doesn't work :c

**Comment by justindi15** [comment] 2020-05-01 01:17
would also like to know this! it seems that destroy does not reset event handlers to vertical scrolling again and reshow the scrollbars. Is there a way to do this?

**Comment by jariz** [comment] 2020-05-25 14:52
@justindi15 `.destroy()` is doing exactly what it should in my tests. Both in removing all events handlers and showing the scrollbar again.
See: https://codesandbox.io/s/rough-waterfall-gutgt?initialpath=vanilla.html&file=/vanilla.js

@Koronos Your code sample is off, `.destroy()` does not make the entire horizontal instance falsely, thus, your sample destroys the instance even if it's already destroyed.
It could be refactored to:
```
   else if (scroll) {
        scroll.destroy();
        scroll = null;
    }
```


@Koronos @justindi15 
Please make an example that reproduces this (codesandbox / github repo), as I can't reproduce it myself.

**Comment by justindi15** [comment] 2020-05-25 17:23
https://codesandbox.io/s/inspiring-fermat-hkfps?initialpath=vanilla.html&file=/vanilla.js

Here is what I have so far. The two issues I need help with are:
1. instantiating the horizontal scroll for desktop and then destroying it for mobile
- In the codesandbox, resize the window size. For the column view it should scroll down and up, but when you resize it up to row view it should scroll horizontally. 

2. when resizing the window the scroll factor does not change so I find that the scroll speed is super high when resizing the window. Is there a way to dynamically adjust scroll factor to window resize?

Thank you so much for your help!

**Comment by jariz** [comment] 2020-05-25 17:54
Your scroll speed is very high because it's initializing a new instance for every resize event. Resize events are typically fired in rapid succession after each other. 

Checking if it's already initialized appears to be enough? 🙂
https://codesandbox.io/s/suspicious-glitter-iy039?file=/vanilla.js&initialpath=vanilla.html

**Comment by jariz** [comment] 2020-05-25 17:56
Additionally, might be a nice feature to have an optional minimal viewport size option in the lib itself so you don't have to bother with all this. 
But for now this is a good workaround.

**Comment by justindi15** [comment] 2020-05-25 17:58
Thank you so much! I feel so dumb cause it was such a small change haha!

**Comment by jariz** [comment] 2020-05-25 18:02
No problem. As this demo also solves @Koronos 's main question, I'm gonna assume this ticket is now fixed.

**Closed by jariz** 2020-05-25 18:02 UTC
